### PR TITLE
Resolve symlinks when comparing notebook paths

### PR DESCRIPTION
**Pull request by clementpoiret**
Hi, first of all, thanks for `zk`! I'm just getting started with it, setting things up.

I encountered a very small problem: As I share the same linux config and sync files between two computers, I have `~/Sync` which is a symlink pointing to different paths on both.

As an example, my config defines `ZK_NOTEBOOK_DIR=/home/clementpoiret/Sync/Notes/zk`, which is itself a symlink to `/mnt/hdd/Sync/Notes/zk`. Using the command `zk new --no-input ($env.ZK_NOTEBOOK_DIR ++ "fleeting") --title "Test"` (some nushell syntax here, sorry for that), give the following error:

```
zk: error: new note: /home/clementpoiret/Sync/Notes/zk/fleeting: path is outside the notebook at /mnt/hdd/Sync/Notes/zk
```

Therefore, I propose to [resolve symlinks](https://pkg.go.dev/github.com/moby/sys/symlink) in the `RelPath` function. I hope you'll be okay with that!

Sincerely,
Clément

### CODE REVIEW

**Comment by tjex** [comment]
Hi Clement, thanks for this pr :) Just a heads up that I'm a bit caught up in a job transition AND a transition from mac to linux. I expect to be looking back into zk next week.

**Comment by clementpoiret** [comment]
No problems, good luck with all that :)

**Comment by tjex** [comment]
@clementpoiret There are some failing tests to do with your changes :scream: . I fixed another unrelated test now, merged and updated this branch.

**Comment by clementpoiret** [comment]
Hi, oops, sorry for that, I have to admit I only verified it worked in my case. I hope this time it's okay for you :)
I'm not good in go btw, so if I made any mistake, I'll try to fix that again

**Comment by tjex** [comment]
As long as tests pass, potential errors are handled and the code is readable and named well, I'm happy. Assign me as a reviewer once ready :+1: 

If you need help with running tests etc, you can read through [contributing](https://github.com/zk-org/zk/blob/main/CONTRIBUTING.md)

Also feel free to ask me questions here.

**Comment by clementpoiret** [comment]
Great, so I can confirm that all tests are passing on my side using `make test` :)
It seems I can't assign a reviewer to this PR however, I may not have the permissions to do so

**Comment by tjex** [comment]
So I had a look through, and all looks  good. But I'm worried that the original issue was not an issue with the code...

I always do a dummy check on PRs, testing the current zk against a PR build.

I tried emulating your issue, by initialising a zk notebook on my usb, creating a symlink at `~/wikis/sym` and setting `ZK_NOTEBOOK_DIR` to `/home/tjex/wikis/sym`. `zk new` worked fine for me... In that a neovim buffer opened wiht the default template showing the path `/mnt/usb/real`. 

Was something about the complexity of your shell command throwing it off? Did you try with a simple `zk new` or `zk list`?

**Comment by clementpoiret** [comment]
Hi, thanks for your time. Thanks for pointing this out, this made me realize this problem happens only when specifying absolute paths, such as:

```sh
cd /tmp
mkdir a/fleeting
ln -s a b
zk init a
touch a/.zk/templates/fleeting.md
$env.ZK_NOTEBOOK_DIR = "/tmp/b"
```

Then, if I do `zk new --no-input ($env.ZK_NOTEBOOK_DIR ++ "/fleeting")` or `zk new --no-input "/tmp/b/fleeting"` I get `zk: error: new note: /tmp/b/fleeting: path is outside the notebook at /tmp/a`.
However, the solution is as straight forward as using relative paths instead: `zk new --no-input "fleeting"`.

Actually, you can consider this a non-issue, sorry for your time :sweat_smile:

**Comment by tjex** [comment]
Not a problem! Glad it's all working on your end too as is :)

**Pull request closed without merging**
